CREATE DATABASE FUTSTATICS;

USE FUTSTATICS;

DROP TABLE TB_TIME_ANO

CREATE TABLE TB_JOGOS
(
    ID               INT IDENTITY (1,1) PRIMARY KEY,
    TIME_MANDANTE    VARCHAR(30)    NOT NULL ,
    PLACAR_MANDANTE  TINYINT        NOT NULL ,
    TIME_VISITANTE   VARCHAR(30)    NOT NULL ,
    PLACAR_VISITANTE TINYINT        NOT NULL ,
    COMPETICAO       VARCHAR(30)    NOT NULL ,
    Ano              INT CHECK (Ano >= 2020 AND Ano <= YEAR(GETDATE())) NOT NULL
)

CREATE TABLE TB_TIME(
    ID_TIME     INT IDENTITY(1,1) PRIMARY KEY,
    NOME        VARCHAR(30) UNIQUE NOT NULL,
    ESTADIO     VARCHAR(60),
    ESTADO      VARCHAR(60),
    CIDADE      VARCHAR(60),
    FOTO        VARCHAR(2048),
    MASCOTE     VARCHAR(20),
)

CREATE TABLE TB_TIME_ANO(
    NOME VARCHAR(30),
    COMPETICAO VARCHAR(30),
    Ano              INT,
    PRIMARY KEY(NOME,COMPETICAO,ANO)
)

CREATE OR ALTER TRIGGER TG_TIME
ON TB_JOGOS
AFTER INSERT
AS
BEGIN
    DECLARE @TIME_MANDANTE    VARCHAR(30);
    DECLARE @TIME_VISITANTE   VARCHAR(30);
    DECLARE C_ADCIONAR CURSOR FOR
        SELECT TIME_MANDANTE,TIME_VISITANTE FROM iNSERTED

    OPEN C_ADCIONAR
    FETCH C_ADCIONAR INTO @TIME_MANDANTE,@TIME_VISITANTE

    WHILE(@@FETCH_STATUS = 0)
    BEGIN
        IF(@TIME_MANDANTE <> (SELECT NOME FROM TB_TIME WHERE NOME = @TIME_MANDANTE))
            INSERT INTO TB_TIME(NOME) VALUES(@TIME_MANDANTE)

        IF(@TIME_VISITANTE <> (SELECT NOME FROM TB_TIME WHERE NOME = @TIME_VISITANTE))
            INSERT INTO TB_TIME(NOME) VALUES(@TIME_MANDANTE)

        FETCH C_ADCIONAR INTO @TIME_MANDANTE,@TIME_VISITANTE
    end
    CLOSE C_ADCIONAR
    DEALLOCATE C_ADCIONAR
end

INSERT INTO TB_JOGOS(TIME_MANDANTE, PLACAR_MANDANTE, TIME_VISITANTE, PLACAR_VISITANTE, COMPETICAO, Ano)
VALUES('ITABAIANA',3,'CONFIANÇA',1,'AMPEONARO SERGIPANO',2023)

--TIME / ANO / COMPETIÇÃO
CREATE OR ALTER TRIGGER TG_TIMEANO
ON TB_JOGOS
AFTER INSERT
AS
BEGIN
    DECLARE @TIME_MANDANTE    VARCHAR(30);
    DECLARE @TIME_VISITANTE   VARCHAR(30);
    DECLARE @COMPETICAO       VARCHAR(30);
    DECLARE @ANO              INT;

    DECLARE C_ADCIONAR CURSOR FOR
        SELECT TIME_MANDANTE, TIME_VISITANTE, COMPETICAO, ANO FROM INSERTED;

    OPEN C_ADCIONAR;
    FETCH NEXT FROM C_ADCIONAR INTO @TIME_MANDANTE, @TIME_VISITANTE, @COMPETICAO, @ANO;

    WHILE (@@FETCH_STATUS = 0)
    BEGIN
        IF NOT EXISTS (
            SELECT 1 FROM TB_TIME_ANO
            WHERE NOME = @TIME_MANDANTE
              AND COMPETICAO = @COMPETICAO
              AND ANO = @ANO
        )
        BEGIN
            INSERT INTO TB_TIME_ANO (NOME, COMPETICAO, Ano)
            VALUES (@TIME_MANDANTE, @COMPETICAO, @ANO);
        END

        IF NOT EXISTS (
            SELECT 1 FROM TB_TIME_ANO
            WHERE NOME = @TIME_VISITANTE
              AND COMPETICAO = @COMPETICAO
              AND ANO = @ANO
        )
        BEGIN
            INSERT INTO TB_TIME_ANO (NOME, COMPETICAO, Ano)
            VALUES (@TIME_VISITANTE, @COMPETICAO, @ANO);
        END

        FETCH NEXT FROM C_ADCIONAR INTO @TIME_MANDANTE, @TIME_VISITANTE, @COMPETICAO, @ANO;
    END

    CLOSE C_ADCIONAR;
    DEALLOCATE C_ADCIONAR;
END




SELECT * FROM TB_TIME_ANO