CREATE DATABASE SAD;

USE SAD;

CREATE TABLE TB_JOGOS
(
    ID               INT IDENTITY (1,1) PRIMARY KEY,
    TIME_MANDANTE    VARCHAR(30),
    PLACAR_MANDANTE  TINYINT,
    TIME_VISITANTE   VARCHAR(30),
    PLACAR_VISITANTE TINYINT,
    COMPETICAO       VARCHAR(30),
    Ano              INT CHECK (Ano >= 2020 AND Ano <= YEAR(GETDATE()))
)

CREATE TB_TIME(
    ID_TIME     INT IDENTITY(1,1) PRIMARY KEY,
    NOME        VARCHAR(30)
)

CREATE TB_TIME_ANO(
    IDTIME INT,
    COMPETICAO VARCHAR(30),
    Ano              INT,
    PRIMARY KEY(IDTIME,COMPETICAO,ANO)
)
CREATE TRIGGER TG_TIME
ON TB_JOGOS
AFTER INSERT, UPDATE
AS
BEGIN
    DECLARE @ID       INT,
    DECLARE @TIME_MANDANTE    VARCHAR(30);
    DECLARE @DEPLACAR_MANDANTE  TINYINT;
    DECLARE @TIME_VISITANTE   VARCHAR(30);
    DECLAREPLACAR_VISITANTE TINYINT;
    DECLARECOMPETICAO       VARCHAR(30);
    DECLARE @Ano              INT; 
end