CREATE DATABASE FUTSTATICS;

USE FUTSTATICS;

CREATE TABLE TB_JOGOS
(
    ID               INT IDENTITY (1,1) PRIMARY KEY,
    TIME_MANDANTE    VARCHAR(30)    NOT NULL ,
    PLACAR_MANDANTE  TINYINT        NOT NULL ,
    TIME_VISITANTE   VARCHAR(30)    NOT NULL ,
    PLACAR_VISITANTE TINYINT        NOT NULL ,
    COMPETICAO       VARCHAR(30)    NOT NULL ,
    Ano              INT CHECK (Ano >= 2020 AND Ano <= YEAR(GETDATE())) NOT NULL ,
)

CREATE TABLE TB_TIME(
    ID_TIME     INT IDENTITY(1,1) PRIMARY KEY,
    NOME        VARCHAR(30) UNIQUE,
    ESTADIO     VARCHAR(60),
    ESTADO      VARCHAR(60),
    CIDADE      VARCHAR(60),
    FOTO        VARCHAR(2048),
    MASCOTE     VARCHAR(20),
    ID_COMPETICAO INT,
    FOREIGN KEY (ID_COMPETICAO) REFERENCES TB_COMPETICAO(ID_COMPETICAO)
)

CREATE TABLE TB_COMPETICAO(
    ID_COMPETICAO   INT IDENTITY (1,1),
    NOME            VARCHAR(60) UNIQUE NOT NULL ,
    TIPO            VARCHAR(30) CHECK (TIPO IN ('NACIONAL','ESTADUAL','REGIONAL'))
)

CREATE TABLE TB_TIME_ANO(
    IDTIME INT,
    ID_COMPETICAO INT,
    Ano              INT,
    FOREIGN KEY (ID_COMPETICAO) REFERENCES TB_COMPETICAO(ID_COMPETICAO),
    PRIMARY KEY(IDTIME,ID_COMPETICAO,ANO)
)

CREATE OR ALTER TRIGGER TG_TIME
ON TB_JOGOS
AFTER INSERT
AS
BEGIN
    DECLARE @TIME_MANDANTE    VARCHAR(30);
    DECLARE @TIME_VISITANTE   VARCHAR(30);

    DECLARE C_ADCIONAR CURSOR FOR
        SELECT TIME_MANDANTE,TIME_VISITANTE FROM iNSERTED

    OPEN C_ADCIONAR
    FETCH C_ADCIONAR INTO @TIME_MANDANTE,@TIME_VISITANTE

    WHILE(@@FETCH_STATUS = 0)
    BEGIN

        IF(@TIME_VISITANTE )
        INSERT INTO TB_TIME(NOME)
        VALUES(@TIME_MANDANTE),(@TIME_VISITANTE)
        FETCH C_ADCIONAR INTO @TIME_MANDANTE,@TIME_VISITANTE
    end
    CLOSE C_ADCIONAR
    DEALLOCATE C_ADCIONAR
end

INSERT INTO TB_JOGOS(TIME_MANDANTE, PLACAR_MANDANTE, TIME_VISITANTE, PLACAR_VISITANTE, COMPETICAO, Ano, FOTO_MANDANTE, FOTO_VISITANTE)
VALUES('ITABAIANA',3,'CONFIANÇA',1,'cAMPEONARO SERGIPANO',2023,'YYY','YYY')

SELECT * FROM TB_TIME